try do go on without git-describe (for tarballs)
Signed-off-by: Nico Schottelius <nico@denkbrett.schottelius.org>

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -41,12 +41,15 @@ versionfiles =  .gitversion .gitversion.m4 .releasedate
 dotfiles =  .gitignore .git/HEAD $(versionfiles)
 distfiles = configure
 
-# regen, if it changed
+# regen, if it changed; ignore if git is missing / fails
 versioncheck:
-	v1="$$(git-describe)"; v2="$$(cat .gitversion)"; \
+	v1="$$(git-describeoooo)" 2>/dev/null; \
+	[ "$$v1" ] || exit 0; \; \
+	v2="$$(cat .gitversion)"; \
 	if [ "$$v1" != "$$v2" ]; then \
+	echo "updating versionfiles"; \
 	date="$$(date +%Y%m%d\ %T\ %z)"; 	\
-	version="$$(git-describe)"; 		\
+	version="$$v1"; 		\
 	echo "define([AC_PACKAGE_VERSION], [$${version} $${date}])" > .gitversion.m4; \
 	echo "$${version}" > .gitversion; \
 	echo "$${date}"    > .releasedate; \
